// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASu2n9ZG1TjPO3daUuxwKl9QOekhJcoqk',
    appId: '1:191885771412:web:35281f3f672a96d7a7aa81',
    messagingSenderId: '191885771412',
    projectId: 'fronthaus-8bc30',
    authDomain: 'fronthaus-8bc30.firebaseapp.com',
    storageBucket: 'fronthaus-8bc30.appspot.com',
    measurementId: 'G-1QQZR84VTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Nj5gS_5e-lFgwu_rl0ZflASzgPNdTfc',
    appId: '1:191885771412:android:72fba2cc2ab93faea7aa81',
    messagingSenderId: '191885771412',
    projectId: 'fronthaus-8bc30',
    storageBucket: 'fronthaus-8bc30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtyMkPr4HA-sdHbrbdEXSPGzfO_qm34Bo',
    appId: '1:191885771412:ios:00e13d4c31a61a49a7aa81',
    messagingSenderId: '191885771412',
    projectId: 'fronthaus-8bc30',
    storageBucket: 'fronthaus-8bc30.appspot.com',
    iosClientId: '191885771412-u2tbse66h766aq1st5qtamirnbiovjb1.apps.googleusercontent.com',
    iosBundleId: 'com.HelloHolo.fronthaus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtyMkPr4HA-sdHbrbdEXSPGzfO_qm34Bo',
    appId: '1:191885771412:ios:00e13d4c31a61a49a7aa81',
    messagingSenderId: '191885771412',
    projectId: 'fronthaus-8bc30',
    storageBucket: 'fronthaus-8bc30.appspot.com',
    iosClientId: '191885771412-u2tbse66h766aq1st5qtamirnbiovjb1.apps.googleusercontent.com',
    iosBundleId: 'com.HelloHolo.fronthaus',
  );
}
